### ISSUE TITLE
Please adhere casing

### ISSUE THREAD

**Issue by infabo** [christophlehmann/httpbasicauth#2]
![image](https://user-images.githubusercontent.com/3999104/63577975-d2414980-c58f-11e9-9135-972fe2148ec1.png)

![image](https://user-images.githubusercontent.com/3999104/63577991-da00ee00-c58f-11e9-90bb-3e4e7fcc7562.png)

**Comment by christophlehmann** [comment]
Casing? PR's are welcome

**Comment by infabo** [comment]
I hope I am welcome.

**Comment by christophlehmann** [comment]
Sure. Thank you!
